### ISSUE TITLE
dumpasn1.c updated, SHA256 mismatch

### ISSUE THREAD

**Issue by yonomitt** [philpennock/homebrew-protocols#2]
I'm getting a SHA256 mismatch when trying to install dumpasn1.

Install command:

`brew install philpennock/protocols/dumpasn1`

After downloading `dumpasn1.c`, it checks the SHA256 checksum and finds a mismatch.

Expected: `4b7c7d92c9593ee58c81019b2c3b7a7ee7450b733d38f196ce7560ee0e34d6b1 `
Actual: `d42b7fb8457b9282ee341429baaaaf0ef7b2310cb28fcf2fc41914e07e8b1370`

**Comment by philpennock** [comment]
Thanks.  The upstream source is unversioned, so the only notification I get of updates is checksums changing.  I'll take a look now.

**Comment by philpennock** [comment]
Resolved (no PR, just pushed) in 7ad39a5

**Comment by amirpervaizQI** [comment]
Hi, I am getting the same error. How to fix it? Thanks.

**Comment by philpennock** [comment]
It just means that the author has updated the files for download so I need to update the checksums after verifying the changes.  I've changed laptops since the last time so I'm trying to hunt down older copies to diff against now.

**Comment by philpennock** [comment]
Should be resolved now.  I don't have a Homebrew setup any more, to test with, though.

**Comment by amirpervaizQI** [comment]
Hi @philpennock, thanks a-lot for fixing it. I was able to install it using macports. I will try with Homebrew again.
